variable "aws_account_num" {}
variable "aws_region" {}
variable "assume_role" {}
variable "aws_user" {}
variable "resource_creation" {}
variable "kms_resource_name" {}
variable "kms_deletion_window_in_days" {}
variable "kms_enable_key_rotation" {}
variable "tag_project_code" {}
variable "tag_department" {}
